# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Administrator\Desktop\论文\程序\电脑端\goodzjh_10_24.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(830, 600)
        
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(20, 90, 54, 12))
        self.label.setObjectName("label")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 110, 160, 80))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 3, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton.setGeometry(QtCore.QRect(200, 170, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.layoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 20, 146, 50))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 0, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 1, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 1, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 0, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.layoutWidget)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 2, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.layoutWidget)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 2, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.centralWidget)
        self.label_12.setGeometry(QtCore.QRect(20, 220, 81, 16))
        self.label_12.setObjectName("label_12")
        self.label_16 = QtWidgets.QLabel(self.centralWidget)
        self.label_16.setGeometry(QtCore.QRect(210, 270, 60, 12))
        self.label_16.setObjectName("label_16")
        self.layoutWidget1 = QtWidgets.QWidget(self.centralWidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(210, 290, 141, 111))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_17 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_17.setObjectName("label_17")
        self.gridLayout_3.addWidget(self.label_17, 1, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_3.addWidget(self.pushButton_3, 3, 0, 1, 2)
        self.label_19 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_19.setObjectName("label_19")
        self.gridLayout_3.addWidget(self.label_19, 0, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_18.setObjectName("label_18")
        self.gridLayout_3.addWidget(self.label_18, 1, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_20.setObjectName("label_20")
        self.gridLayout_3.addWidget(self.label_20, 0, 1, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_3.addWidget(self.pushButton_2, 2, 0, 1, 2)
        self.graphicsView = QtWidgets.QGraphicsView(self.centralWidget)
        self.graphicsView.setGeometry(QtCore.QRect(620, 480, 181, 91))
        self.graphicsView.setStyleSheet("border-image: url(:/my_pic/1.jpg);")
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralWidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(20, 290, 137, 171))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.dang0 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.dang0.setObjectName("dang0")
        self.gridLayout_4.addWidget(self.dang0, 2, 0, 1, 2)
        self.fanfszt = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.fanfszt.setObjectName("fanfszt")
        self.gridLayout_4.addWidget(self.fanfszt, 1, 1, 1, 1)
        self.dang3 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.dang3.setObjectName("dang3")
        self.gridLayout_4.addWidget(self.dang3, 5, 0, 1, 2)
        self.dang1 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.dang1.setObjectName("dang1")
        self.gridLayout_4.addWidget(self.dang1, 3, 0, 1, 2)
        self.label_22 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_22.setObjectName("label_22")
        self.gridLayout_4.addWidget(self.label_22, 0, 0, 1, 1)
        self.dang2 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.dang2.setObjectName("dang2")
        self.gridLayout_4.addWidget(self.dang2, 4, 0, 1, 2)
        self.fansbzt = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.fansbzt.setObjectName("fansbzt")
        self.gridLayout_4.addWidget(self.fansbzt, 0, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_21.setObjectName("label_21")
        self.gridLayout_4.addWidget(self.label_21, 1, 0, 1, 1)
        self.label_fan = QtWidgets.QLabel(self.centralWidget)
        self.label_fan.setGeometry(QtCore.QRect(20, 270, 54, 12))
        self.label_fan.setObjectName("label_fan")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.centralWidget)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(400, 290, 161, 111))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_26 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_26.setObjectName("label_26")
        self.gridLayout_5.addWidget(self.label_26, 2, 0, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_27.setObjectName("label_27")
        self.gridLayout_5.addWidget(self.label_27, 3, 0, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_28.setObjectName("label_28")
        self.gridLayout_5.addWidget(self.label_28, 0, 1, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_25.setObjectName("label_25")
        self.gridLayout_5.addWidget(self.label_25, 0, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_23.setObjectName("label_23")
        self.gridLayout_5.addWidget(self.label_23, 1, 0, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_29.setObjectName("label_29")
        self.gridLayout_5.addWidget(self.label_29, 1, 1, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_4.setEnabled(True)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_5.addWidget(self.pushButton_4, 2, 1, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_5.addWidget(self.pushButton_5, 3, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.centralWidget)
        self.label_24.setGeometry(QtCore.QRect(400, 270, 54, 12))
        self.label_24.setObjectName("label_24")
        self.label_30 = QtWidgets.QLabel(self.centralWidget)
        self.label_30.setGeometry(QtCore.QRect(170, 410, 451, 81))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(26)
        self.label_30.setFont(font)
        self.label_30.setText("")
        self.label_30.setObjectName("label_30")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.centralWidget)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(350, 80, 207, 103))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.comboBox_2 = QtWidgets.QComboBox(self.gridLayoutWidget_4)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.gridLayout_6.addWidget(self.comboBox_2, 2, 1, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.gridLayoutWidget_4)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_6.addWidget(self.comboBox, 1, 1, 1, 1)
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.gridLayoutWidget_4)
        self.dateTimeEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2019, 4, 1), QtCore.QTime(0, 0, 0)))
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.gridLayout_6.addWidget(self.dateTimeEdit, 0, 1, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_33.setObjectName("label_33")
        self.gridLayout_6.addWidget(self.label_33, 1, 0, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_34.setObjectName("label_34")
        self.gridLayout_6.addWidget(self.label_34, 2, 0, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_32.setObjectName("label_32")
        self.gridLayout_6.addWidget(self.label_32, 0, 0, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_6.addWidget(self.pushButton_6, 3, 0, 1, 2)
        self.label_13 = QtWidgets.QLabel(self.centralWidget)
        self.label_13.setGeometry(QtCore.QRect(110, 220, 191, 21))
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.label_31 = QtWidgets.QLabel(self.centralWidget)
        self.label_31.setGeometry(QtCore.QRect(350, 60, 54, 12))
        self.label_31.setObjectName("label_31")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 830, 23))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menuBar)
        self.actionQUIT = QtWidgets.QAction(MainWindow)
        self.actionQUIT.setObjectName("actionQUIT")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menu.addAction(self.actionQUIT)
        self.menu.addAction(self.actionAbout)
        self.menuBar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "信息采集"))
        self.label_4.setText(_translate("MainWindow", "气压(Pa)："))
        self.label_2.setText(_translate("MainWindow", "温度(摄氏度)："))
        self.label_3.setText(_translate("MainWindow", "湿度(%)："))
        self.pushButton.setText(_translate("MainWindow", "获取数据"))
        self.label_8.setText(_translate("MainWindow", "MQTT连接状态："))
        self.label_10.setText(_translate("MainWindow", "设备状态："))
        self.label_11.setText(_translate("MainWindow", "离线"))
        self.label_9.setText(_translate("MainWindow", "连接失败"))
        self.label_14.setText(_translate("MainWindow", "设备电压(V)："))
        self.label_15.setText(_translate("MainWindow", "未知"))
        self.label_12.setText(_translate("MainWindow", "最近更新时间："))
        self.label_16.setText(_translate("MainWindow", "插座控制："))
        self.label_17.setText(_translate("MainWindow", "插座状态："))
        self.pushButton_3.setText(_translate("MainWindow", "关"))
        self.label_19.setText(_translate("MainWindow", "设备状态："))
        self.label_18.setText(_translate("MainWindow", "未知"))
        self.label_20.setText(_translate("MainWindow", "离线"))
        self.pushButton_2.setText(_translate("MainWindow", "开"))
        self.dang0.setText(_translate("MainWindow", "零档"))
        self.fanfszt.setText(_translate("MainWindow", "未知"))
        self.dang3.setText(_translate("MainWindow", "三档"))
        self.dang1.setText(_translate("MainWindow", "一档"))
        self.label_22.setText(_translate("MainWindow", "设备状态："))
        self.dang2.setText(_translate("MainWindow", "二档"))
        self.fansbzt.setText(_translate("MainWindow", "离线"))
        self.label_21.setText(_translate("MainWindow", "风扇状态："))
        self.label_fan.setText(_translate("MainWindow", "风扇控制："))
        self.label_26.setText(_translate("MainWindow", "火焰报警："))
        self.label_27.setText(_translate("MainWindow", "人体报警："))
        self.label_28.setText(_translate("MainWindow", "离线"))
        self.label_25.setText(_translate("MainWindow", "设备状态："))
        self.label_23.setText(_translate("MainWindow", "空气质量："))
        self.label_29.setText(_translate("MainWindow", "未知"))
        self.pushButton_4.setText(_translate("MainWindow", "关"))
        self.pushButton_5.setText(_translate("MainWindow", "关"))
        self.label_24.setText(_translate("MainWindow", "报警控制："))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "请选择"))
        self.comboBox.setItemText(0, _translate("MainWindow", "请选择"))
        self.comboBox.setItemText(1, _translate("MainWindow", "风扇"))
        self.comboBox.setItemText(2, _translate("MainWindow", "插座"))
        self.comboBox.setItemText(3, _translate("MainWindow", "火焰报警"))
        self.comboBox.setItemText(4, _translate("MainWindow", "人体报警"))
        self.label_33.setText(_translate("MainWindow", "选择设备"))
        self.label_34.setText(_translate("MainWindow", "选择操作"))
        self.label_32.setText(_translate("MainWindow", "选择时间"))
        self.pushButton_6.setText(_translate("MainWindow", "发送命令"))
        self.label_31.setText(_translate("MainWindow", "定时任务："))
        self.menu.setTitle(_translate("MainWindow", "菜单"))
        self.actionQUIT.setText(_translate("MainWindow", "Quit"))
        self.actionAbout.setText(_translate("MainWindow", "About"))

import my_test_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    MainWindow.setWindowIcon(QIcon('myICO.ico'))
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

